name: Tests & Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: ShellCheck
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install ShellCheck
      run: sudo apt-get update && sudo apt-get install -y shellcheck
    
    - name: Lint shell scripts
      run: |
        echo "🔍 Vérification des scripts Bash..."
        shellcheck bin/gittbd bin/gittbds
        shellcheck lib/loader.sh lib/config.sh
        shellcheck lib/core/*.sh
        shellcheck lib/domain/*.sh
        shellcheck lib/commands/*.sh
        echo "✅ Lint OK"

  tests:
    name: Tests Suite
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Git
      run: |
        git config --global user.name "CI Bot"
        git config --global user.email "ci@gittbd.test"
    
    - name: Run tests
      run: |
        chmod +x tests/run_tests.sh
        bash tests/run_tests.sh
    
    - name: Test summary
      if: always()
      run: |
        if [ $? -eq 0 ]; then
          echo "✅ Tous les tests passent"
        else
          echo "❌ Des tests ont échoué"
          exit 1
        fi